name: 08-05- Repo Variables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: use repo variables
        run: |
          echo "DEBUG: ${{ vars.debug_var }}"